---
promptToReturnFromSubprocess: false

os:
  editCommand: "nvr -s -l" # see 'Configuring File Editing' section
  editCommandTemplate: "{{editor}} +{{line}} -- {{filename}}"
  openCommand: "nvr -s -l {{filename}}"

git:
  autorefresh: false

keybinding:
  files:
    commitChanges: "C"
    commitChangesWithEditor: "c"
