# `sheldon` configuration file
# ----------------------------
#
# You can modify this file directly or you can use one of the following
# `sheldon` commands which are provided to assist in editing the config file:
#
# - `sheldon add` to add a new plugin to the config file
# - `sheldon edit` to open up the config file in the default editor
# - `sheldon remove` to remove a plugin from the config file
#
# See the documentation for more https://github.com/rossmacarthur/sheldon#readmeshell = "zsh"

[templates]
fpath = 'fpath+=( "{{ dir }}" )'
defer = { value = 'zsh-defer source "{{ file }}"', each = true }

# zsh plugins
[plugins.zsh-defer]
github = "romkatv/zsh-defer"

[plugins.zsh-utils-editor]
local = "~/.config/zsh/plugins/zsh-utils"
use = ["editor/*.zsh"]

[plugins.zsh-vi-mode]
github = "jeffreytse/zsh-vi-mode"

# specify completion sources before module
[plugins.compeltions]
github = "zsh-users/zsh-completions"

# initalize history options and completion
[plugins.zsh-utils]
local = "~/.config/zsh/plugins/zsh-utils"
use = ["history/*.zsh", "directory/*.zsh"]

# time consuming plugins
[plugins.fast-syntax-highlighting]
github = "zdharma/fast-syntax-highlighting"
apply = ["defer"]

# history needs to come after highlighting
[plugins.zsh-history-substring-search]
github = "zsh-users/zsh-history-substring-search"

[plugins.zsh-autosuggestions]
github = "zsh-users/zsh-autosuggestions"
apply = ["defer"]

[plugins.zsh-utils-completion]
local = "~/.config/zsh/plugins/zsh-utils"
use = ["completion/*.zsh"]
